In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [4]:
X,y=load_iris(return_X_y=True)

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [6]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [7]:
import numpy as np
(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[ 0.34875024, -0.63670913,  0.5848042 ,  0.0507131 ],
       [-0.25953507, -0.17224046,  0.47115804,  0.44759826],
       [ 1.80863499, -0.4044748 ,  1.49397348,  0.84448342],
       [-1.47610569,  0.2922282 , -1.29035745, -1.27223743],
       [-1.84107687, -0.17224046, -1.46082669, -1.40453248],
       [ 0.95703555, -0.17224046,  0.41433496,  0.31530321],
       [ 0.59206437, -0.4044748 ,  1.09621192,  0.84448342],
       [ 0.71372143,  0.2922282 ,  0.47115804,  0.44759826],
       [ 1.20034968, -0.63670913,  0.64162728,  0.31530321],
       [ 0.83537849, -0.17224046,  1.03938884,  0.84448342],
       [-0.137878  ,  1.68563421, -1.11988821, -1.13994238],
       [ 0.71372143, -0.86894347,  0.92574268,  0.97677848],
       [ 1.07869262, -1.33341214,  1.20985808,  0.84448342],
       [-0.50284919, -0.17224046,  0.47115804,  0.44759826],
       [-0.86782038,  1.68563421, -1.23353437, -1.13994238],
       [-0.98947744, -2.49458381, -0.09707276, -0.213877  ],
       [-0.74616331,  0.

In [8]:
X_train_scaled
# 1️⃣ StandardScaler standardizes numeric features by removing the mean and scaling to unit variance (mean=0, std=1).
# 2️⃣ Formula: z = (x - μ) / σ, where μ is the mean and σ is the standard deviation of each feature.
# 3️⃣ It ensures all features contribute equally, improving model stability and training performance.
# 4️⃣ Always fit the scaler on training data, then apply the same transformation to the test data.
# 5️⃣ Not required for tree-based models (like Random Forest or Decision Tree) since they are scale-invariant.


array([[ 0.34875024, -0.63670913,  0.5848042 ,  0.0507131 ],
       [-0.25953507, -0.17224046,  0.47115804,  0.44759826],
       [ 1.80863499, -0.4044748 ,  1.49397348,  0.84448342],
       [-1.47610569,  0.2922282 , -1.29035745, -1.27223743],
       [-1.84107687, -0.17224046, -1.46082669, -1.40453248],
       [ 0.95703555, -0.17224046,  0.41433496,  0.31530321],
       [ 0.59206437, -0.4044748 ,  1.09621192,  0.84448342],
       [ 0.71372143,  0.2922282 ,  0.47115804,  0.44759826],
       [ 1.20034968, -0.63670913,  0.64162728,  0.31530321],
       [ 0.83537849, -0.17224046,  1.03938884,  0.84448342],
       [-0.137878  ,  1.68563421, -1.11988821, -1.13994238],
       [ 0.71372143, -0.86894347,  0.92574268,  0.97677848],
       [ 1.07869262, -1.33341214,  1.20985808,  0.84448342],
       [-0.50284919, -0.17224046,  0.47115804,  0.44759826],
       [-0.86782038,  1.68563421, -1.23353437, -1.13994238],
       [-0.98947744, -2.49458381, -0.09707276, -0.213877  ],
       [-0.74616331,  0.

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)


# 1️⃣ MinMaxScaler scales features to a fixed range, usually [0, 1].
# 2️⃣ Formula: X_scaled = (X - X_min) / (X_max - X_min).
# 3️⃣ Preserves the shape of the original distribution.
# 4️⃣ Useful for algorithms sensitive to feature magnitude (e.g., KNN, Neural Networks).
# 5️⃣ Fit on training data, then transform both train and test sets.

In [10]:
X_train_scaled

array([[0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.08333333, 0.5       , 0.06779661, 0.04166667],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667,

In [11]:
X_min=np.min(X_train, axis=0)
X_max=np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)
# this gives same output as X_train_scaled but in numpy and less efficient way

array([[0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.08333333, 0.5       , 0.06779661, 0.04166667],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667,