In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [14]:
X,y=load_iris(return_X_y=True)

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [16]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [17]:
import numpy as np
(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[-1.34300897,  0.27145429, -1.159506  , -1.25319886],
       [-0.27962943, -0.67962645,  0.62712581,  0.99506487],
       [ 0.54744354,  0.74699466,  1.00610832,  1.49467904],
       [ 0.07483041, -0.20408608,  0.24814331,  0.37054717],
       [ 0.54744354, -0.44185626,  1.00610832,  0.74525779],
       [-1.81562209, -0.20408608, -1.43020779, -1.3781024 ],
       [-0.16147615, -0.20408608,  0.24814331, -0.00416345],
       [ 0.31113697, -0.20408608,  0.62712581,  0.74525779],
       [-0.515936  , -0.20408608,  0.41056438,  0.37054717],
       [ 1.02005666, -0.20408608,  0.78954689,  1.3697755 ],
       [ 0.66559682,  0.03368411,  0.95196796,  0.74525779],
       [-1.1067024 , -1.392937  ,  0.41056438,  0.62035425],
       [-1.22485568,  0.03368411, -1.159506  , -1.25319886],
       [ 1.84712963, -0.67962645,  1.27681011,  0.87016133],
       [ 1.25636323,  0.27145429,  1.06024868,  1.3697755 ],
       [ 0.31113697, -0.20408608,  0.46470474,  0.24564363],
       [-0.98854912,  0.

In [18]:
X_train_scaled
# 1️⃣ StandardScaler standardizes numeric features by removing the mean and scaling to unit variance (mean=0, std=1).
# 2️⃣ Formula: z = (x - μ) / σ, where μ is the mean and σ is the standard deviation of each feature.
# 3️⃣ It ensures all features contribute equally, improving model stability and training performance.
# 4️⃣ Always fit the scaler on training data, then apply the same transformation to the test data.
# 5️⃣ Not required for tree-based models (like Random Forest or Decision Tree) since they are scale-invariant.


array([[-1.34300897,  0.27145429, -1.159506  , -1.25319886],
       [-0.27962943, -0.67962645,  0.62712581,  0.99506487],
       [ 0.54744354,  0.74699466,  1.00610832,  1.49467904],
       [ 0.07483041, -0.20408608,  0.24814331,  0.37054717],
       [ 0.54744354, -0.44185626,  1.00610832,  0.74525779],
       [-1.81562209, -0.20408608, -1.43020779, -1.3781024 ],
       [-0.16147615, -0.20408608,  0.24814331, -0.00416345],
       [ 0.31113697, -0.20408608,  0.62712581,  0.74525779],
       [-0.515936  , -0.20408608,  0.41056438,  0.37054717],
       [ 1.02005666, -0.20408608,  0.78954689,  1.3697755 ],
       [ 0.66559682,  0.03368411,  0.95196796,  0.74525779],
       [-1.1067024 , -1.392937  ,  0.41056438,  0.62035425],
       [-1.22485568,  0.03368411, -1.159506  , -1.25319886],
       [ 1.84712963, -0.67962645,  1.27681011,  0.87016133],
       [ 1.25636323,  0.27145429,  1.06024868,  1.3697755 ],
       [ 0.31113697, -0.20408608,  0.46470474,  0.24564363],
       [-0.98854912,  0.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)


# 1️⃣ MinMaxScaler scales features to a fixed range, usually [0, 1].
# 2️⃣ Formula: X_scaled = (X - X_min) / (X_max - X_min).
# 3️⃣ Preserves the shape of the original distribution.
# 4️⃣ Useful for algorithms sensitive to feature magnitude (e.g., KNN, Neural Networks).
# 5️⃣ Fit on training data, then transform both train and test sets.

In [27]:
X_train_scaled

array([[0.11111111, 0.45454545, 0.10169492, 0.04166667],
       [0.36111111, 0.27272727, 0.66101695, 0.79166667],
       [0.55555556, 0.54545455, 0.77966102, 0.95833333],
       [0.44444444, 0.36363636, 0.54237288, 0.58333333],
       [0.55555556, 0.31818182, 0.77966102, 0.70833333],
       [0.        , 0.36363636, 0.01694915, 0.        ],
       [0.38888889, 0.36363636, 0.54237288, 0.45833333],
       [0.5       , 0.36363636, 0.66101695, 0.70833333],
       [0.30555556, 0.36363636, 0.59322034, 0.58333333],
       [0.66666667, 0.36363636, 0.71186441, 0.91666667],
       [0.58333333, 0.40909091, 0.76271186, 0.70833333],
       [0.16666667, 0.13636364, 0.59322034, 0.66666667],
       [0.13888889, 0.40909091, 0.10169492, 0.04166667],
       [0.86111111, 0.27272727, 0.86440678, 0.75      ],
       [0.72222222, 0.45454545, 0.79661017, 0.91666667],
       [0.5       , 0.36363636, 0.61016949, 0.54166667],
       [0.19444444, 0.59090909, 0.10169492, 0.20833333],
       [0.36111111, 0.22727273,

In [ ]:
X_min=np.min(X_train, axis=0)
X_max=np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)
# this gives same output as X_train_scaled but in numpy and less efficient way

array([[0.11111111, 0.45454545, 0.10169492, 0.04166667],
       [0.36111111, 0.27272727, 0.66101695, 0.79166667],
       [0.55555556, 0.54545455, 0.77966102, 0.95833333],
       [0.44444444, 0.36363636, 0.54237288, 0.58333333],
       [0.55555556, 0.31818182, 0.77966102, 0.70833333],
       [0.        , 0.36363636, 0.01694915, 0.        ],
       [0.38888889, 0.36363636, 0.54237288, 0.45833333],
       [0.5       , 0.36363636, 0.66101695, 0.70833333],
       [0.30555556, 0.36363636, 0.59322034, 0.58333333],
       [0.66666667, 0.36363636, 0.71186441, 0.91666667],
       [0.58333333, 0.40909091, 0.76271186, 0.70833333],
       [0.16666667, 0.13636364, 0.59322034, 0.66666667],
       [0.13888889, 0.40909091, 0.10169492, 0.04166667],
       [0.86111111, 0.27272727, 0.86440678, 0.75      ],
       [0.72222222, 0.45454545, 0.79661017, 0.91666667],
       [0.5       , 0.36363636, 0.61016949, 0.54166667],
       [0.19444444, 0.59090909, 0.10169492, 0.20833333],
       [0.36111111, 0.22727273,